name: Deploy to Kubernetes
description: Deploy to Kubernetes
inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  aws-region:
    description: AWS Region
    required: true
    default: us-east-1
  image:
    description: Image to deploy
    required: true
  kube_config:
    description: base64 encoded kube config
    required: true
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      if: success()
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.5.4"

    - name: Set image
      working-directory: ./kubernetes
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize build . > ../ci-deployment.yaml

    - name: Deploy image to k8s cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube_config }}
      with:
        args: apply -f ./ci-deployment.yaml
