kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-mixpanel-deployment
  namespace: stablecog
  labels:
    app: sc-mixpanel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-mixpanel
  template:
    metadata:
      labels:
        app: sc-mixpanel
    spec:
      containers:
        - name: sc-mixpanel
          image: replaceme
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 80
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: stablecog-secrets
      imagePullSecrets:
        - name: regcred
