name: CI

on:
  push:
    branches: [master]

jobs:
  build_and_publish_image:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@master

      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Login to registry
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: true
          tags: appditto/stablecog-mixpanel:${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_ID }}

  deploy_image:
    name: Deploy Image
    needs: build_and_publish_image
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/actions/k8s-deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          image: appditto/stablecog-mixpanel:${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_ID }}
          kube_config: ${{ secrets.KUBE_CONFIG_DATA }}

